# Generated by Django 4.2.21 on 2025-05-20 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_price',
            new_name='total',
        ),
    ]
