# Generated by Django 4.2.21 on 2025-05-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_total_price_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_alt',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
